### ISSUE TITLE
[BUG] Error login steam `Unexpected Server Error`

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#34]
![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/727c9677-79cd-4a1e-9b79-5fc95b0ead22)

```
The table `public.UserPreference` does not exist in the current database.
    at In.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6854)
    at In.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6188)
    at In.request (/app/node_modules/@prisma/client/runtime/library.js:122:5896)
    at l (/app/node_modules/@prisma/client/runtime/library.js:127:10871)
    at getUserPreference (file:///app/build/server/index.js?t=1711416431282.3552:5274:17)
    at loader$a (file:///app/build/server/index.js?t=1711416431282.3552:5292:17)
    at Object.callRouteLoaderRR (/app/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
    at callLoaderOrAction (/app/node_modules/@remix-run/router/router.ts:4043:16)
    at async Promise.all (index 0)
    at loadRouteData (/app/node_modules/@remix-run/router/router.ts:3320:19) {
  code: 'P2021',
  clientVersion: '5.11.0',
  meta: { modelName: 'UserPreference', table: 'public.UserPreference' }
}
GET /api/action/preferences 500 - - 4.435 ms
GET /craft?_data=routes%2Fcraft._index 200 - - 1.469 ms
PrismaClientKnownRequestError: 
Invalid `prisma.userPreference.findFirst()` invocation:


The table `public.UserPreference` does not exist in the current database.
    at In.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6854)
    at In.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6188)
    at In.request (/app/node_modules/@prisma/client/runtime/library.js:122:5896)
    at l (/app/node_modules/@prisma/client/runtime/library.js:127:10871)
    at getUserPreference (file:///app/build/server/index.js?t=1711416431282.3552:5274:17)
    at loader$a (file:///app/build/server/index.js?t=1711416431282.3552:5292:17)
    at Object.callRouteLoaderRR (/app/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
    at callLoaderOrAction (/app/node_modules/@remix-run/router/router.ts:4043:16)
    at async Promise.all (index 0)
    at loadRouteData (/app/node_modules/@remix-run/router/router.ts:3320:19) {
  code: 'P2021',
  clientVersion: '5.11.0',
  meta: { modelName: 'UserPreference', table: 'public.UserPreference' }
}
GET /api/action/preferences 500 - - 7.249 ms
GET / 200 - - 38.676 ms
GET /?_data=routes%2F_index 200 - - 3.158 ms
POST /api/action/sync 200 - - 32.939 ms
POST /api/action/sync 200 - - 18.959 ms
POST /api/action/sync 200 - - 24.252 ms
POST /api/action/sync 200 - - 22.451 ms
POST /api/action/sync 200 - - 59.589 ms
GET /api/equipped/76561198152215513.json 200 - - 6.419 ms
POST /api/action/sync 200 - - 19.926 ms
GET /api/equipped/76561198380275130.json 200 - - 4.035 ms
GET /api/equipped/76561198964993976.json 200 - - 2.369 ms
```
However, even after this error, the login is still done when I enter the website link again.

https://cs2.zkservidores.com/

**Comment by ianlucas** [comment]
You need to apply database migrations with every deploy.
